require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'AmazonAuthRNExample' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'AmazonAuthRNExampleTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
    
    installer.pods_project.targets.each do |target|
      # find the right target
      if target.name == 'RNAmazonAuthentication'
        target.build_configurations.each do |config|
          # add library search paths
          config.build_settings['FRAMEWORK_SEARCH_PATHS'] = ["$(PROJECT_DIR)/.."]
        end
      end
    end
    
  end
end

target 'AmazonAuthRNExample-tvOS' do
  # Pods for AmazonAuthRNExample-tvOS

  target 'AmazonAuthRNExample-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
